### ISSUE TITLE
Programmatically calling show() and hide()

### ISSUE THREAD

**Issue by PlkMarudny** [Kapsonfire-DE/svelte-ktippy#5]
Is this possible in general?

**Comment by Kapsonfire** [comment]
At current state - not - since we dont have the tippy instance at itsself. 
Im not sure how to solve it in best way...
One idea is to add a store/object parameter to it where the component is writing the tippy instance in it.


```
let tippyStorage = writable<any>();

<div use:tooltip={{component: TooltipItem, instanceStorage: tippyStorage, tippyprops: {item: myItem}}>
  Hover me
</div>

```

something like this

what do you think about it?

**Comment by PlkMarudny** [comment]
Yeah, this should work, however it is ugly somehow.
I asked because when a popup is made interactive (for example for context menu usage), it is kind of hard to close it later without having access to the inance methods (or I am missing something)

**Comment by PlkMarudny** [comment]
Basically it would be a 'globalStore' plugin mentioned here: https://atomiks.github.io/tippyjs/v6/plugins/ ?

**Comment by Kapsonfire** [comment]
basically yes - but in a svelte way

**Comment by PlkMarudny** [comment]
Seems to be a great idea.

**Comment by Kapsonfire** [comment]
Solved in https://github.com/Kapsonfire-DE/svelte-ktippy/releases/tag/1.2.0

**Comment by Kapsonfire** [comment]
@PlkMarudny please tell me if this solves all your problems :-D

**Comment by PlkMarudny** [comment]
Thanks for your prompt action, however I am not really sure how to use `tippyStore`. If imported into a component like: 
`import { tippyStore } from 'svelte-ktippy/tippyStore';`
it is not working, i.e it is empty.

**Comment by PlkMarudny** [comment]
It works on CodeSandBox, however: https://codesandbox.io/s/svelte-ktippy-forked-rmjv4?file=/App.svelte

**Comment by Kapsonfire** [comment]
``` 	
<button id="popover" use:popover={props}>
    Hover me for popover
  </button>
```

The Anchornode you are using on the popover/toolip needs an id attribute. then the tippystore is filled with id as key....

$tippyStore.popover.show()

**Comment by Kapsonfire** [comment]
https://codesandbox.io/s/svelte-ktippy-forked-lr8kr?file=/App.svelte

**Comment by PlkMarudny** [comment]
I am sorry, somehow I pasted a wrong link, this is the right one, it works: https://codesandbox.io/s/svelte-ktippy-forked-rmjv4?file=/TestTooltip.svelte
The similar code does not work, however in the real app, well.. 
Anyway, thank you very much.

**Comment by PlkMarudny** [comment]
Actually, I have found an issue. In my code, when `tippyStore` is imported using
`import { tippyStore } from 'svelte-ktippy/tippyStore';` it does not work - the store is empty.
When I import it using an absolute path, i.e.: 
`import { tippyStore } from '/node_modules/svelte-ktippy/tippyStore';`, it works, I  can see and access stored `instance` variables.
Maybe it is a Vite thing?

**Comment by Kapsonfire** [comment]
I can't reproduce it. it could be some hot-reloading issues with vite

**Comment by PlkMarudny** [comment]
No worries, this is not related to the package, I will nail down the
problem later on. Thanks for support!
