### ISSUE TITLE
Parameters passed to component are not reactive

### ISSUE THREAD

**Issue by PlkMarudny** [Kapsonfire-DE/svelte-ktippy#6]
Parameters passed to component seem to be not reactive?

**Comment by Kapsonfire** [comment]
Can you give example code to test it? Maybe online in codesandbox?

**Comment by PlkMarudny** [comment]
This one -> https://codesandbox.io/s/svelte-ktippy-forked-eyu7o?file=/App.svelte

**Comment by Kapsonfire** [comment]
This provides no example where the reactivity is needed like changing a prop on button click. And what should be reactive. The props for the tippy wrapper or the rendered component?

**Comment by PlkMarudny** [comment]
Ach, ok. By pressing "press me" button an item is added to the array, that is passed down the component - the component renders the last item in the array. The array is updated, but the component does not re-render the updated array.

**Comment by PlkMarudny** [comment]
I guess the update() method is missing https://svelte.dev/docs#template-syntax-element-directives-use-action

**Comment by Kapsonfire** [comment]
Solved in 1.2.1

**Comment by PlkMarudny** [comment]
Works perfectly now, thank you very much for your prompt action.
