### ISSUE TITLE
attach tooltip to SVG node? 

### ISSUE THREAD

**Issue by jeffmacinnes** [Kapsonfire-DE/svelte-ktippy#7]
I'm wondering if it's possible to attach the tooltip to an svg node, such that the tooltip appears when the node is hovered? 

It looks like the tooltip is a `div` that gets appended to the anchor node on hover. If that's the case, I can't think of a way this would work. Would really appreciate any tips or advice. Thanks!

Something like:
```
<svg>
    <rect
      use:tooltip={{
        component: MyTooltipComponent,
      }}
      x="0"
      y="0"
      width="100"
      height="100"
      fill="#ccc"
    />
</svg>
```

**Comment by Kapsonfire** [comment]
did you try this way already? you can make the tooltip to append to body with the appendTo property

**Comment by Kapsonfire** [comment]
Closing due inactivity - Please let me know if you need further help.
